---
title: "security quick analysis"
author: "Janis Corona"
date: "8/5/2020"
output: html_document
---


```{r}
securitydf <- read.csv('./security/security.csv', sep=',', header=F, na.strings=c('',' ','NA'),
               stringsAsFactors = F)
header <- read.csv('./security/tableBusinessesHeader_security.csv', sep=',', header=T,
                   na.strings=c('',' ','NA'),
               stringsAsFactors = F)
colnames(securitydf) <- header$x
head(securitydf,10)
```


```{r}
sDF <- securitydf[!duplicated(securitydf$businessType),]
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```
